# set TARGET_HOST to dns/ip of proxy
# set LOGSTASH_HOST to dns/ip of logstash host

version: '3'
services:
  elasticsearch:
    image: elasticsearch:2.1.1
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.elasticsearch==true"

  logstash:
    image: accenture/adop-logstash:0.1.0
    environment:
      - "constraint:tier==public"
      - LS_HEAP_SIZE=1024m
    ports:
      - "12201:12201/udp"
      - "25826:25826/udp"
      - "5000:5000/tcp"
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.logstash==true"

  kibana:
    image: kibana:4.3.1
    command: kibana
    depends_on:
      - elasticsearch
      - logstash
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.kibana==true"

  proxy:
    container_name: proxy
    image: "accenture/adop-nginx:0.3.0"
    volumes:
      - nginx_config:/etc/nginx
      - nginx_releasenote:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - swarm_net
    environment:
      - "LDAP_SERVER=${LDAP_SERVER}"
      - "LDAP_USERNAME=${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      - "LDAP_PASSWORD=${LDAP_PWD}"
      - "LDAP_USER_BASE_DN=${LDAP_USER_BASE_DN},${LDAP_FULL_DOMAIN}"
      - "LDAP_GROUP_ATTRIBUTE=member"
      - "LDAP_USER_ID_ATTRIBUTE=cn"
      - "LDAP_USER_OBJECT_CLASS=inetOrgPerson"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.proxy==true"

  ldap:
    container_name: ldap
    image: accenture/adop-ldap:0.1.3
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_static:/etc/ldap
    ports:
      - "389:389"
    networks:
      - swarm_net
    environment:
      - "INITIAL_ADMIN_USER=${INITIAL_ADMIN_USER}"
      - "INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}"
      - "JENKINS_PASSWORD=${JENKINS_PWD}"
      - "GERRIT_PASSWORD=${GERRIT_PWD}"
      - "SLAPD_PASSWORD=${LDAP_PWD}"
      - "SLAPD_DOMAIN=${LDAP_DOMAIN}"
      - "SLAPD_FULL_DOMAIN=${LDAP_FULL_DOMAIN}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.proxy==true"

  gerrit-mysql:
    container_name: gerrit-mysql
    image: mysql:5.6.25
    volumes:
      - gerrit_mysql_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - swarm_net
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_SQL}
      MYSQL_USER: ${GERRIT_MYSQL_USER}
      MYSQL_PASSWORD: ${GERRIT_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${GERRIT_MYSQL_DATABASE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.gerrit==true"

  gerrit:
    container_name: gerrit
    image: accenture/adop-gerrit:0.1.3
    volumes:
      - git_repos:/var/git/repos
      - gerrit_review_site:/var/gerrit/review_site
    privileged: true
    user: root
    expose:
      - "8080"
      - "29418"
    networks:
      - swarm_net
    depends_on:
      - gerrit-mysql
    environment:
      - "dependency:container==gerrit-mysql"
      - "REPO_PATH=/var/git/repos"
      - "WEBURL=${PROTO}://${TARGET_HOST}/gerrit/"
      - "DATABASE_TYPE=mysql"
      - "DB_HOSTNAME=gerrit-mysql"
      - "DB_PORT=3306"
      - "DB_NAME=${GERRIT_MYSQL_DATABASE}"
      - "DB_USER=${GERRIT_MYSQL_USER}"
      - "DB_PASSWORD=${GERRIT_MYSQL_PASSWORD}"
      - "AUTH_LOGOUTURL=${PROTO}://${TARGET_HOST}/gerrit/"
      - "AUTH_TYPE=LDAP"
      - "GERRIT_PASSWORD=${PASSWORD_GERRIT}"
      - "JENKINS_PASSWORD=${PASSWORD_JENKINS}"
      - "INITIAL_ADMIN_USER=${INITIAL_ADMIN_USER}"
      - "INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD_PLAIN}"
      - "LDAP_SERVER=${LDAP_SERVER}"
      - "LDAP_ACCOUNTBASE=${LDAP_FULL_DOMAIN}"
      - "LDAP_ACCOUNTPATTERN=${LDAP_ACCOUNTPATTERN}"
      - "LDAP_ACCOUNTFULLNAME=${LDAP_ACCOUNTFULLNAME}"
      - "LDAP_ACCOUNTEMAILADDRESS=mail"
      - "LDAP_USERNAME=${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      - "LDAP_PASSWORD=${LDAP_PWD}"
      - "LDAP_GROUPBASE=${LDAP_GROUP_BASE_DN},${LDAP_FULL_DOMAIN}"
      - "LDAP_GROUPPATTERN=${LDAP_GROUPPATTERN}"
      - "LDAP_GROUPMEMBERPATTERN=${LDAP_GROUPMEMBERPATTERN}"
      - "HTTPD_LISTENURL=proxy-${PROTO}://0.0.0.0:8080/gerrit"
      - "USER_NAME=${GERRIT_USER_NAME}"
      - "USER_EMAIL=${GERRIT_USER_EMAIL}"
      - "DOWNLOAD_SCHEME=http"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.gerrit==true"

  sensu-uchiwa:
    container_name: sensu-uchiwa
    image: sstarcher/uchiwa:0.15.0
    environment:
      SENSU_HOSTNAME: sensu-api
      SENSU_DC_NAME: Sensu
    expose:
      - "3000"
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sensu==true"

  sensu-api:
    container_name: sensu-api
    image: accenture/adop-sensu:0.2.0
    volumes:
      - sensu_api_conf:/etc/sensu/conf.d
    command: api
    depends_on:
      - sensu-rabbitmq
      - sensu-redis
      - sensu-server
    expose:
      - "4567"
    networks:
      - swarm_net
    environment:
      TRANSPORT_NAME: rabbitmq
      RABBITMQ_HOST: sensu-rabbitmq
      REDIS_HOST: sensu-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sensu==true"

  sensu-server:
    container_name: sensu-server
    image: accenture/adop-sensu:0.2.0
    volumes:
      - sensu_server_conf:/etc/sensu/conf.d
    command: server
    depends_on:
      - sensu-rabbitmq
      - sensu-redis
    networks:
      - swarm_net
    environment:
      API_HOST: sensu-api
      RABBITMQ_HOST: sensu-rabbitmq
      REDIS_HOST: sensu-redis
      TRANSPORT_NAME: rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sensu==true"

  sensu-client:
    container_name: sensu-client
    image: accenture/adop-sensu:0.2.0
    volumes:
      - sensu_client_conf:/etc/sensu/conf.d
    command: client
    depends_on:
      - sensu-server
    environment:
      TRANSPORT_NAME: rabbitmq
      CLIENT_NAME: core
      CLIENT_ADDRESS: ${PROXY_NODE}
      RABBITMQ_HOST: sensu-rabbitmq
      JENKINS_PREFIX: jenkins
      CLIENT_SUBSCRIPTIONS: ""
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sensu==true"

  sensu-rabbitmq:
    container_name: sensu-rabbitmq
    image: rabbitmq:3.5.7-management
    volumes:
      - sensu_rabbitmq_data:/var/lib/rabbitmq
    expose:
      - "5672"
      - "5671"
      - "15672"
      - "15671"
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sensu==true"

  sensu-redis:
    container_name: sensu-redis
    image: redis:3.0.7
    volumes:
      - sensu_redis_data:/data
    expose:
      - "6379"
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sensu==true"

  sonar-mysql:
    container_name: sonar-mysql
    image: mysql:5.6.25
    volumes:
      - sonar_mysql_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - swarm_net
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_SQL}
      MYSQL_USER: ${SONAR_MYSQL_USER}
      MYSQL_PASSWORD: ${SONAR_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SONAR_MYSQL_DATABASE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sonar==true"

  sonar:
    container_name: sonar
    image: accenture/adop-sonar:0.2.0
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    expose:
      - "9000"
    networks:
      - swarm_net
    depends_on:
      - sonar-mysql
    environment:
      - "dependency:container==sonar-mysql"
      - "SONARQUBE_JDBC_USERNAME=${SONAR_MYSQL_USER}"
      - "SONARQUBE_JDBC_PASSWORD=${SONAR_MYSQL_PASSWORD}"
      - "LDAP_URL=ldap://${LDAP_SERVER}"
      - "LDAP_BIND_DN=${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      - "LDAP_BIND_PASSWORD=${LDAP_PWD}"
      - "LDAP_USER_BASE_DN=${LDAP_USER_BASE_DN},${LDAP_FULL_DOMAIN}"
      - "LDAP_USER_REQUEST=(&(objectClass=inetOrgPerson)(uid={login}))"
      - "LDAP_USER_REAL_NAME_ATTRIBUTE=displayName"
      - "LDAP_USER_EMAIL_ATTRIBUTE=mail"
      - "LDAP_GROUP_BASE_DN=${LDAP_GROUP_BASE_DN},${LDAP_FULL_DOMAIN}"
      - "LDAP_GROUP_REQUEST=(&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))"
      - "LDAP_GROUP_ID_ATTRIBUTE=cn"
      - "SONARQUBE_JDBC_URL=jdbc:mysql://sonar-mysql:3306/${SONAR_MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.sonar==true"

  jenkins:
    container_name: jenkins
    image: accenture/adop-jenkins:0.2.6
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "50000:50000"
    expose:
      - "8080"
      - "50000"
    networks:
      - swarm_net
    privileged: true
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
      ROOT_URL: "${PROTO}://${TARGET_HOST}/jenkins/"
      LDAP_SERVER: "${LDAP_SERVER}"
      LDAP_ROOTDN: "${LDAP_FULL_DOMAIN}"
      LDAP_USER_SEARCH_BASE: "${LDAP_USER_BASE_DN}"
      LDAP_USER_SEARCH: "${LDAP_USER_SEARCH}"
      LDAP_GROUP_SEARCH_BASE: "${LDAP_GROUP_BASE_DN}"
      LDAP_GROUP_SEARCH_FILTER: ""
      LDAP_GROUP_MEMBERSHIP_FILTER: ""
      LDAP_MANAGER_DN: "${LDAP_MANAGER_DN}"
      LDAP_MANAGER_PASSWORD: ${LDAP_PWD}
      LDAP_INHIBIT_INFER_ROOTDN: "false"
      LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: "false"
      LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: "displayName"
      LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: "mail"
      LDAP_GROUP_NAME_ADMIN: "${LDAP_GROUP_NAME_ADMIN}"
      INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}
      GERRIT_HOST_NAME: "gerrit"
      GERRIT_FRONT_END_URL: "http://gerrit:8080/gerrit"
      GERRIT_JENKINS_USERNAME: "${GERRIT_JENKINS_USERNAME}"
      GERRIT_JENKINS_PASSWORD: ${PASSWORD_JENKINS}
      SONAR_SERVER_URL: "http://sonar:9000/sonar/"
      SONAR_ACCOUNT_LOGIN: ${SONAR_ACCOUNT_LOGIN}
      SONAR_ACCOUNT_PASSWORD: ${PASSWORD_JENKINS}
      SONAR_DB_URL: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&amp;characterEncoding=utf8"
      SONAR_DB_LOGIN: ${SONAR_DB_LOGIN}
      SONAR_DB_PASSWORD: ${SONAR_DB_PASSWORD}
      SONAR_PLUGIN_VERSION: ""
      SONAR_ADDITIONAL_PROPS: ""
      SONAR_RUNNER_VERSION: "2.4"
      ANT_VERSION: "1.9.4"
      MAVEN_VERSION: "3.0.5"
      NODEJS_VERSION: "6.9.4"
      NODEJS_GLOBAL_PACKAGES: "grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1"
      NODEJS_PACKAGES_REFRESH_HOURS: "72"
      GIT_GLOBAL_CONFIG_NAME: "ADOP Jenkins"
      GROOVY_VERSION: "2.4.8"
      GIT_GLOBAL_CONFIG_EMAIL: "jenkins@${LDAP_DOMAIN}"
      DOCKER_TLS_VERIFY: ${DOCKER_TLS_VERIFY}
      DOCKER_HOST: ${DOCKER_HOST}
      DOCKER_CLIENT_CERT_PATH: ${DOCKER_CLIENT_CERT_PATH}
      DOCKER_NETWORK_NAME: ${CUSTOM_NETWORK_NAME}
      CARTRIDGE_SOURCES: ${CARTRIDGE_SOURCES}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.jenkins==true"

  jenkins-slave:
    container_name: jenkins-slave
    image: accenture/adop-jenkins-slave:0.1.4
    volumes:
      - jenkins_slave_home:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - swarm_net
    environment:
      SLAVE_LABELS: "aws ldap java8 docker"
      SWARM_PASSWORD: ${PASSWORD_JENKINS}
      SLAVE_EXECUTORS: ${SLAVE_EXECUTORS}
      INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.jenkins==true"

  nexus:
    container_name: nexus
    image:  accenture/adop-nexus:0.1.3
    volumes:
      - nexus_sonatype_work:/sonatype-work
    ports:
      - "8081:8081"
    networks:
      - swarm_net
    environment:
      - "NEXUS_BASE_URL=${PROTO}://${TARGET_HOST}/nexus"
      - "LDAP_SEARCH_BASE=${LDAP_FULL_DOMAIN}"
      - "LDAP_ENABLED=true"
      - "LDAP_URL=ldap"
      - "LDAP_BIND_DN=${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      - "LDAP_USER_PASSWORD_ATTRIBUTE=userPassword"
      - "LDAP_USER_BASE_DN=${LDAP_USER_BASE_DN}"
      - "LDAP_GROUP_BASE_DN=${LDAP_GROUP_BASE_DN}"
      - "LDAP_BIND_PASSWORD=${LDAP_PWD}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.nexus==true"

  ldap-ltb:
    container_name: ldap-ltb
    image: accenture/adop-ldap-ltb:0.1.0
    expose:
      - "80"
    networks:
      - swarm_net
    environment:
      LDAP_LTB_URL: "ldap://${LDAP_SERVER}"
      LDAP_LTB_DN: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      LDAP_LTB_PWD: "${LDAP_PWD}"
      LDAP_LTB_BS: "${LDAP_FULL_DOMAIN}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.ldap==true"

  ldap-phpadmin:
    container_name: ldap-phpadmin
    image: accenture/adop-ldap-phpadmin:0.1.0
    expose:
      - "80"
    networks:
      - swarm_net
    environment:
      LDAP_SERVER_NAME: "LDAP"
      LDAP_SERVER_HOST: "ldap"
      LDAP_SERVER_PORT: "389"
      LDAP_SERVER_BIND_ID: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      LDAP_SERVER_BASE_DN: "${LDAP_FULL_DOMAIN}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.ldap==true"

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:2.53.0
    expose:
      - "4444"
    networks:
      - swarm_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.selenium==true"

  selenium-node-chrome:
    container_name: selenium-node-chrome
    image: selenium/node-chrome:2.53.0
    networks:
      - swarm_net
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-chrome.json"
      REMOTE_HOST: "http://selenium-node-chrome:5555"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.selenium==true"

  selenium-node-firefox:
    container_name: selenium-node-firefox
    image: selenium/node-firefox:2.53.0
    networks:
      - swarm_net
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-firefox.json"
      REMOTE_HOST: "http://selenium-node-firefox:5555"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - "node.labels.selenium==true"

volumes:
  elasticsearch_data:
  nginx_config:
  nginx_releasenote:
  ldap_db:
  ldap_static:
  gerrit_mysql_data:
  git_repos:
  gerrit_review_site:
  sensu_api_conf:
  sensu_server_conf:
  sensu_client_conf:
  sensu_rabbitmq_data:
  sensu_redis_data:
  sonar_mysql_data:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  jenkins_slave_home:
  jenkins_home:
  nexus_sonatype_work:

networks:
  swarm_net:
    driver: overlay
